In [9]:
import pandas as pd
import json
import seaborn as sns
import matplotlib.pyplot as mpl

In [10]:
subreddits = [
    # main subreddits
    "soccer",
    "premierleague",
    "football",
    "theother14",

    # big clubs
    "reddevils",    # man u
    "LiverpoolFC",
    "gunners",      # arsenal
    "chelseafc",
    "MCFC",         # man city
    "coys",         # spurs
    
    # others
    "FantasyPL",
    "Championship",
    
    # diversity subreddits
    "realmadrid",
    "Barca",
    "fcbayern",
    "psg",
    "ACMilan",
]

get and display raw information

In [11]:
df = pd.read_csv("../reddit-scrape-data/temp.csv")
df

,author,author_flair,title,content,post_id,date,upvotes,upvote_ratio,num_comments,subreddit
0,n00bball,:r_soccer_user:,FIFA COO: World Cup 'too big' to be postponed ...,NaN,1rpq5w1,1.773127e+09,6,0.88,9,soccer
1,Roller95,:Ajax:,"[VI] After a meeting, Feyenoord management hav...",NaN,1rppmma,1.773125e+09,10,0.92,4,soccer
2,Friendly_Raise9142,:Chelsea_s_Rampant_Lion:,Premier league home table (1st slide) and away...,NaN,1rpnymf,1.773119e+09,36,0.93,20,soccer
3,Delmer9713,:Honduras:,[CNN] Five players from the Iran Women's Natio...,NaN,1rpm1dz,1.773113e+09,739,0.95,74,soccer
4,kundu123,NaN,Iraq coach Arnold asks FIFA to reschedule its ...,NaN,1rplxef,1.773113e+09,42,0.89,4,soccer
...,...,...,...,...,...,...,...,...,...,...
16824,Claija79,Bot Mexicano 🇲🇽,[PBP] Thiago Silva would like to return to the...,NaN,1pqoacr,1.766159e+09,144,1.00,25,ACMilan
16825,Claija79,Bot Mexicano 🇲🇽,"[LucaCohen] Milan, talks underway with Paulo T...",NaN,1pqmy5n,1.766156e+09,40,0.99,5,ACMilan
16826,mercurialsaliva,:2007:,"[Schira] Santiago Gimenez underwent, today in ...",NaN,1pqm3b4,1.766154e+09,100,0.98,31,ACMilan
16827,bertvrapi,:9_: Marco van Basten :van_basten:,Redbird looking to obtain new private credit l...,NaN,1pqkz2f,1.766151e+09,39,0.98,28,ACMilan
16828,AutoModerator,NaN,Free Talk Friday,Che succede?\n\nNew users check out the [New M...,1pq7pf6,1.766106e+09,8,1.00,86,ACMilan

filter out all those that are before the latest season (1 aug 2025)

In [13]:
df['date'] = pd.to_datetime(df['date'], unit='s', utc=True)   

startDate = pd.to_datetime("2025-08-01", utc=True)
df = df[df['date'] >= startDate]
df

C:\Users\josqu\AppData\Local\Temp\ipykernel_30160\437231175.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['date'] = pd.to_datetime(df['date'], unit='s', utc=True)

,author,author_flair,title,content,post_id,date,upvotes,upvote_ratio,num_comments,subreddit
0,n00bball,:r_soccer_user:,FIFA COO: World Cup 'too big' to be postponed ...,NaN,1rpq5w1,2026-03-10 07:11:54+00:00,6,0.88,9,soccer
1,Roller95,:Ajax:,"[VI] After a meeting, Feyenoord management hav...",NaN,1rppmma,2026-03-10 06:39:05+00:00,10,0.92,4,soccer
2,Friendly_Raise9142,:Chelsea_s_Rampant_Lion:,Premier league home table (1st slide) and away...,NaN,1rpnymf,2026-03-10 05:03:04+00:00,36,0.93,20,soccer
3,Delmer9713,:Honduras:,[CNN] Five players from the Iran Women's Natio...,NaN,1rpm1dz,2026-03-10 03:26:02+00:00,739,0.95,74,soccer
4,kundu123,NaN,Iraq coach Arnold asks FIFA to reschedule its ...,NaN,1rplxef,2026-03-10 03:20:50+00:00,42,0.89,4,soccer
...,...,...,...,...,...,...,...,...,...,...
16824,Claija79,Bot Mexicano 🇲🇽,[PBP] Thiago Silva would like to return to the...,NaN,1pqoacr,2025-12-19 15:43:23+00:00,144,1.00,25,ACMilan
16825,Claija79,Bot Mexicano 🇲🇽,"[LucaCohen] Milan, talks underway with Paulo T...",NaN,1pqmy5n,2025-12-19 14:49:11+00:00,40,0.99,5,ACMilan
16826,mercurialsaliva,:2007:,"[Schira] Santiago Gimenez underwent, today in ...",NaN,1pqm3b4,2025-12-19 14:12:27+00:00,100,0.98,31,ACMilan
16827,bertvrapi,:9_: Marco van Basten :van_basten:,Redbird looking to obtain new private credit l...,NaN,1pqkz2f,2025-12-19 13:22:48+00:00,39,0.98,28,ACMilan
16828,AutoModerator,NaN,Free Talk Friday,Che succede?\n\nNew users check out the [New M...,1pq7pf6,2025-12-19 01:01:39+00:00,8,1.00,86,ACMilan

get only post content for manual classification

In [ ]:
toClassify = df[['title']]
toClassify = toClassify[toClassify['title'] != "Free Talk Friday"]
toClassify

# send to csv
toClassify.to_csv("classify.csv", index = False)

                                                   title
0      FIFA COO: World Cup 'too big' to be postponed ...
1      [VI] After a meeting, Feyenoord management hav...
2      Premier league home table (1st slide) and away...
3      [CNN] Five players from the Iran Women's Natio...
4      Iraq coach Arnold asks FIFA to reschedule its ...
...                                                  ...
16823                       Referee highlights vs Napoli
16824  [PBP] Thiago Silva would like to return to the...
16825  [LucaCohen] Milan, talks underway with Paulo T...
16826  [Schira] Santiago Gimenez underwent, today in ...
16827  Redbird looking to obtain new private credit l...

[16517 rows x 1 columns]