# Data exploration and cleaning

In [1]:
import pandas as pd
import json
import seaborn as sns
import matplotlib.pyplot as mpl

In [2]:
subreddits = [
    # main subreddits
    "soccer",
    "premierleague",
    "football",
    "theother14",

    # big clubs
    "reddevils",    # man u
    "LiverpoolFC",
    "gunners",      # arsenal
    "chelseafc",
    "MCFC",         # man city
    "coys",         # spurs
    
    # others
    "FantasyPL",
    "Championship",
    
    # diversity subreddits
    "realmadrid",
    "Barca",
    "fcbayern",
    "psg",
    "ACMilan",
]

## Get the raw data taken reddit_scraper.ipynb

In [20]:
df = pd.read_csv("../reddit-scrape-data/data.csv", encoding="utf-8")
df.head(5)

,author,author_flair,title,content,post_id,date,upvotes,upvote_ratio,num_comments,comments,subreddit
0,Sparky-moon,:transpride::AS_Roma:,The Congolese courts have sentenced Jean-Guy B...,"On Tuesday, March 10, 2026, the Congolese cour...",1rpxyqy,1.773152e+09,5,1.00,1,['Some old rich fuck getting put away for misu...,soccer
1,OkayFine101,:Manchester_United:,[@WestHam] West Ham United's dressing room cel...,NaN,1rpxx4c,1.773152e+09,8,1.00,2,[],soccer
2,SolitasTT,:Liverpool:,Eni Aluko wins Joey Barton libel case over pos...,NaN,1rpxsqj,1.773151e+09,11,0.87,5,['Not a good day for Joey Barton. Hopefully ma...,soccer
3,Sparky-moon,:transpride::AS_Roma:,FIFA has cut over $100 million from its operat...,The people who raised the matter of the budget...,1rpxspb,1.773151e+09,3,1.00,1,"[""It wouldn't surprise me if there a comes a d...",soccer
4,AutoModerator,NaN,Daily Discussion,# Welcome to the [r/soccer](https://old.reddit...,1rpxqc2,1.773151e+09,5,1.00,7,['I will riot if we don’t get ucl football nex...,soccer

## Data Filtering
Filter out all posts that are before the latest season (1 aug 2025)

In [27]:
df['date'] = pd.to_datetime(df['date'], unit='s', utc=True)   

startDate = pd.to_datetime("2025-08-01", utc=True)
df = df[df['date'] >= startDate]
df.head(5)

,author,author_flair,title,content,post_id,date,upvotes,upvote_ratio,num_comments,comments,subreddit
0,Sparky-moon,:transpride::AS_Roma:,The Congolese courts have sentenced Jean-Guy B...,"On Tuesday, March 10, 2026, the Congolese cour...",1rpxyqy,2026-03-10 14:10:24+00:00,5,1.00,1,['Some old rich fuck getting put away for misu...,soccer
1,OkayFine101,:Manchester_United:,[@WestHam] West Ham United's dressing room cel...,NaN,1rpxx4c,2026-03-10 14:08:37+00:00,8,1.00,2,[],soccer
2,SolitasTT,:Liverpool:,Eni Aluko wins Joey Barton libel case over pos...,NaN,1rpxsqj,2026-03-10 14:03:41+00:00,11,0.87,5,['Not a good day for Joey Barton. Hopefully ma...,soccer
3,Sparky-moon,:transpride::AS_Roma:,FIFA has cut over $100 million from its operat...,The people who raised the matter of the budget...,1rpxspb,2026-03-10 14:03:38+00:00,3,1.00,1,"[""It wouldn't surprise me if there a comes a d...",soccer
4,AutoModerator,NaN,Daily Discussion,# Welcome to the [r/soccer](https://old.reddit...,1rpxqc2,2026-03-10 14:01:03+00:00,5,1.00,7,['I will riot if we don’t get ucl football nex...,soccer

get only post content for manual labelling

In [5]:
def combine(row):
    comments = row['comments']
    
    if isinstance(comments, list):
        print("LIST")
        return [row['title']] + comments
    elif pd.isna(comments):
        return [row['title']]
    else:  # single string comment
        print(type(comments))
        return [row['title'], comments]

In [6]:
# convert list of comments treated as a string into an actual list of comments
# "["comment 1", "comment 2"]" into ["comment 1", "comment 2"]
import ast

df['comments'] = df['comments'].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else x
)

In [7]:
temp = df.loc[df['title'] != "Free Talk Friday", ['title', 'comments']].copy()

# combine title and comments
combined = [[title] + comments for title, comments in zip(temp['title'], temp['comments'])]

toClassify = (
    pd.DataFrame({'A': combined})
      .explode('A', ignore_index=True)
      .assign(B=None)
)

In [8]:
# need to fix encoding issue
toClassify['A'] = (
    toClassify['A']
    .str.encode('utf-8')
    .str.decode('utf-8')
)

In [ ]:
# send to csv
toClassify.to_csv("classify.csv", index = False, encoding = 'utf-8-sig')

## Data cleaning
Clean the data by performing microtext normalization and lemmatization.

We also remove comments that were deleted, or contain images that are not helpful.

In [10]:
import re
from microtext import microtext

Normalise by replacing URLs, punctuation and performing microtext normalisation

In [11]:
def normalize_text(text: str) -> str:
    text = text.lower()
    # Replace URLs and mentions
    text = re.sub(r"http\S+|www\.\S+", " URL ", text)
    text = re.sub(r"@\w+", " USER ", text)
    
    # Collapse repeated punctuation
    text = re.sub(r"([!?])\1+", r"\1\1", text)
    
    # handle oov words
    tokens = re.findall(r"\b\w+\b|[^\w\s]", text)
    
    normalized_tokens = [
        microtext[token][0] if token in microtext else token
        for token in tokens
    ]
    
    text = " ".join(normalized_tokens)

    # strip extra whitespace
    text = re.sub(r"\s+", " ", text).strip()
    
    return text

Remove undesired entries from comments

In [12]:
def clean_comments(comments: list):
    # convert str comment to list
    # if theres only one comment it will be a string instead of list so this is to standardise it
    if isinstance(comments, str):
        comments = [comments]
    elif isinstance(comments, list):
        comments = comments
    else:
        return []
    
    cleaned = []
    for c in comments:
        if not isinstance(c, str):
            continue
        
        c_strip = c.strip().lower()
        
        if re.fullmatch(r"\[\s*(deleted|removed)\s*\]", c_strip):
            continue
        if re.search(r"<\s*image\s*=", c_strip):
            continue
        
        cleaned.append(c)
    
    return cleaned

In [13]:
df["comments"] = df["comments"].apply(clean_comments)
df["comments"] = df["comments"].apply(
    lambda comments: [normalize_text(c) for c in comments]
)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5100 entries, 0 to 5099
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   author        5077 non-null   object
 1   author_flair  3161 non-null   object
 2   title         5100 non-null   object
 3   content       2182 non-null   object
 4   post_id       5100 non-null   object
 5   date          5100 non-null   datetime64[ns, UTC]
 6   upvotes       5100 non-null   int64
 7   upvote_ratio  5100 non-null   float64
 8   num_comments  5100 non-null   int64
 9   comments      5100 non-null   object
 10  subreddit     5100 non-null   object
dtypes: datetime64[ns, UTC](1), float64(1), int64(2), object(7)
memory usage: 438.4+ KB

get number of words and unique words in the entire corpus

In [31]:
from collections import Counter

# Combine all words from column 'A'
all_words = toClassify['A'].str.lower().str.split().explode()

# Total word count
total_words = len(all_words)

# Word frequency counter
word_freq = Counter(all_words)

# Number of unique words
unique_words = len(word_freq)

# Unique words ordered by frequency
words_by_freq = word_freq.most_common()  # list of (word, count) tuples

print(f"Total words: {total_words}")
print(f"Unique words: {unique_words}")
print(f"\nWord frequencies:\n{words_by_freq}")

Total words: 3660953
Unique words: 136622

Word frequencies: